### ISSUE TITLE
basename: invalid option -- 'b'

### ISSUE THREAD

**Issue by nitin194** [plyint/encpass.sh#24]
Hello @ahnick,

Hope you are doing well. We are trying to use encpass in centos v 6.5. But we are facing some errors. Could you please suggest what went wrong?

[eretail@eretailapp01 DO_NOT_DELETE]$ . encpass.sh
```
basename: invalid option -- 'b'
Try `basename --help' for more information.
```
[eretail@eretailapp01 DO_NOT_DELETE]$ ll
total 52
```
-rwxr-xr-x 1 eretail eretail 47467 Jun 23 13:11 encpass.sh
-rwxr-xr-x 1 eretail eretail  1349 Jun  3 10:13 start_services.sh
```
[eretail@eretailapp01 DO_NOT_DELETE]$ cat /etc/*release
```
CentOS release 6.5 (Final)
LSB_VERSION=base-4.0-amd64:base-4.0-noarch:core-4.0-amd64:core-4.0-noarch
CentOS release 6.5 (Final)
CentOS release 6.5 (Final)
```
[eretail@eretailapp01 DO_NOT_DELETE]$

**Comment by ahnick** [comment]
That's odd.  Can you provide the following info?

- What shell environment are you all using? (bash? zsh? csh?)
- What's the output of running `./encpass.sh ls`?
- What's the output of `./encpass.sh version`?

Also, if you can narrow down to which line it is failing on in the script that would be helpful as well.

**Comment by nitin194** [comment]
Thank you for reverting back. Below are the details

[eretail@eretailapp01 DO_NOT_DELETE]$ echo $SHELL
`/bin/bash`
[eretail@eretailapp01 DO_NOT_DELETE]$ ./encpass.sh ls
`vineretail-db-password`
[eretail@eretailapp01 DO_NOT_DELETE]$ ./encpass.sh version
```
tag version: v4.1.3
SHA256 Checksum: 81471821093a150785d01a1a66af0414ad0485a4277982b806247a6550b76b61  ./encpass.sh
```

**Comment by ahnick** [comment]
so it looks like the script is working pretty well when used from the command line, but the sourcing of the script seems to be the issue?  What happens when you use `source encpass.sh` instead of `. encpass.sh`?

Also, are you just trying to source the script from the command line for troubleshooting?  Generally, you only the source the script when inside another script.  Do you have another script where you were trying to source encpass.sh into it and it is failing with this same error?

**Comment by nitin194** [comment]
Thanks, @ahnick for the prompt response. yes, I was trying to test the encpass externally without any script. Maybe that's the problem ... when I sourced it inside a script, it seems to be working fine. I will get back to you in case of any concerns

**Comment by ahnick** [comment]
Okay, sounds good.  It is still odd that it doesn't source in your shell directly.  Normally, what happens is if you source the script directly into the shell then it adds all the functions, but it doesn't produce any output.  The only line that involves basename when you source the script is line 1229.
```
if [ "$(basename "$0")" = "encpass.sh" ]; then
```

I'd be curious to know if you added the following lines just above line 1229 what the output is:
```
echo "name=$0"
echo "basename=$(basename "$0")"
```

On mine I get 
```
name=bash
basename=bash
```

**Comment by nitin194** [comment]
Hello @ahnick 
sorry for being late to respond. Here is the output if we add those lines at the desired position

```
[eretail@eretailapp01 DO_NOT_DELETE]$ source encpass.sh
name=-bash
basename: invalid option -- 'b'
Try `basename --help' for more information.
basename=
basename: invalid option -- 'b'
Try `basename --help' for more information.
```

**Comment by ahnick** [comment]
Okay, so that's the problem.  Argument 0 ($0), which is coming into the script is coming in as "-bash" instead of "bash" when it is being invoked from the command line.  This gets interpreted as a parameter to basename.  Is this typical of Bash on CentOS to pass that in that way?  Or have you specially configured the shell to set argument 0 that way? 

If this is standard behavior for Bash on CentOS, then I could strip any preceding hyphens off of argument 0 before passing it to the basename command and then that should avoid the error.

**Comment by ahnick** [comment]
Also, what's the output of `echo $0` on your shell in bash?

**Comment by nitin194** [comment]
No we did not configured shell in any way to show like that ... below is the output

```
[eretail@eretailapp01 ~]$ echo $0
-bash
[eretail@eretailapp01 ~]$ cat /etc/*release
CentOS release 6.5 (Final)
LSB_VERSION=base-4.0-amd64:base-4.0-noarch:core-4.0-amd64:core-4.0-noarch
CentOS release 6.5 (Final)
CentOS release 6.5 (Final)
```

**Comment by ahnick** [comment]
I'm unable to replicate this issue when pulling down an older version of CentOS.  Below I pulled CentOS 6.6 (they didn't have 6.5) from Docker Hub and you will see that argument 0 is output as just "bash".

```
$ sudo docker run -it centos:6.6 bash
Unable to find image 'centos:6.6' locally
6.6: Pulling from library/centos
5dd797628260: Pull complete 
Digest: sha256:32b80b90ba17ed16e9fa3430a49f53ff6de0d4c76ad8631717a1373d5921fa26
Status: Downloaded newer image for centos:6.6
[root@dc498b35b4c2 /]# echo $0
bash
[root@dc498b35b4c2 /]# cat /etc/*release
CentOS release 6.6 (Final)
CentOS release 6.6 (Final)
CentOS release 6.6 (Final)
```

I still think there may be something special about the system you are using that is prepending the shell name with a hyphen (i.e. "-bash" instead of "bash")  I would check the .bashrc and .profile files of both the user and the system to make sure there is nothing initializing that to -bash.  According to bash documentation for GNU on special parameters (https://www.gnu.org/software/bash/manual/html_node/Special-Parameters.html) $0 should be the shell name when executed from the command line.  If you have another system you could try it out on that might be a good test as well.

I may still implement some additional logic just to strip off any preceding hyphens anyway just to make the script a bit more robust and resistant to errors, but it certainly doesn't seem like the shell is behaving properly.

**Comment by nitin194** [comment]
I also checked the bashrc and bash_profile file but there is nothing of that sort that you are pointing to. Still, Thank you @ahnick for all the support you extended in my issue. It is resolved for me now

**Comment by ahnick** [comment]
I've addressed this issue in the latest release (https://github.com/plyint/encpass.sh/releases/tag/v4.1.4) You should no longer see this error if you include encpass.sh directly from the command line.
